export type RoutePageKind =
  | 'dashboard'
  | 'accounts'
  | 'tasks'
  | 'scheduler'
  | 'copywriter'
  | 'providers'
  | 'setup'
  | 'settings'
  | 'placeholder';

export interface ShellNavGroup {
  key: string;
  title: string;
  order: number;
}

export interface ShellRouteManifestItem {
  path: string;
  aliases?: string[];
  name: string;
  pageKind: RoutePageKind;
  navGroup: string;
  navOrder: number;
  legacyRouteKey: string;
  migrationStatus: 'implemented' | 'placeholder';
  title: string;
  eyebrow: string;
  summary: string;
}

export const shellNavGroups: ShellNavGroup[] = [
  { key: 'overview', title: '总览工作台', order: 10 },
  { key: 'ops', title: '运营管理', order: 20 },
  { key: 'automation', title: '自动化任务', order: 30 },
  { key: 'content', title: '内容与 AI', order: 40 },
  { key: 'analysis', title: '数据分析', order: 50 },
  { key: 'system', title: '系统与工具', order: 60 },
];

export const shellRouteManifest: ShellRouteManifestItem[] = [
  {
    path: '/',
    name: 'dashboard',
    pageKind: 'dashboard',
    navGroup: 'overview',
    navOrder: 10,
    legacyRouteKey: 'dashboard',
    migrationStatus: 'implemented',
    title: '概览看板',
    eyebrow: '总览工作台',
    summary: '集中查看系统健康、核心指标、任务状态与最近动态。',
  },
  {
    path: '/operations-center',
    name: 'operations-center',
    pageKind: 'placeholder',
    navGroup: 'ops',
    navOrder: 10,
    legacyRouteKey: 'operations-center',
    migrationStatus: 'placeholder',
    title: '运营中心',
    eyebrow: '运营排期中台',
    summary: '统一协调账号、素材、任务和排期资源，作为逐页迁移的运营总入口。',
  },
  {
    path: '/accounts',
    name: 'account',
    pageKind: 'accounts',
    navGroup: 'ops',
    navOrder: 20,
    legacyRouteKey: 'account',
    migrationStatus: 'implemented',
    title: '账号管理',
    eyebrow: '账号治理',
    summary: '管理账号主数据、人工状态、系统状态、风险状态、审计中心与生命周期动作。',
  },
  {
    path: '/device-management',
    name: 'device-management',
    pageKind: 'placeholder',
    navGroup: 'ops',
    navOrder: 30,
    legacyRouteKey: 'device-management',
    migrationStatus: 'placeholder',
    title: '设备管理',
    eyebrow: '环境治理',
    summary: '统一查看浏览器隔离环境、代理、指纹和设备账号绑定关系。',
  },
  {
    path: '/asset-center',
    name: 'asset-center',
    pageKind: 'placeholder',
    navGroup: 'ops',
    navOrder: 40,
    legacyRouteKey: 'asset-center',
    migrationStatus: 'placeholder',
    title: '素材中心',
    eyebrow: '资源管理',
    summary: '集中管理素材归属、标签、状态与账号绑定关系。',
  },
  {
    path: '/order-management',
    name: 'order-management',
    pageKind: 'placeholder',
    navGroup: 'ops',
    navOrder: 50,
    legacyRouteKey: 'order-management',
    migrationStatus: 'placeholder',
    title: '订单管理',
    eyebrow: '订单处理中心',
    summary: '统一查看订单状态、异常订单和退款进度。',
  },
  {
    path: '/service-center',
    name: 'service-center',
    pageKind: 'placeholder',
    navGroup: 'ops',
    navOrder: 60,
    legacyRouteKey: 'service-center',
    migrationStatus: 'placeholder',
    title: '客服中心',
    eyebrow: '客服工单中心',
    summary: '统一管理客服工单、自动分配规则和响应时效。',
  },
  {
    path: '/refund-processing',
    name: 'refund-processing',
    pageKind: 'placeholder',
    navGroup: 'ops',
    navOrder: 70,
    legacyRouteKey: 'refund-processing',
    migrationStatus: 'placeholder',
    title: '退款处理',
    eyebrow: '退款审批中心',
    summary: '集中管理退款申请、审批流程和财务对账。',
  },
  {
    path: '/tasks',
    aliases: ['/task-queue'],
    name: 'task-queue',
    pageKind: 'tasks',
    navGroup: 'automation',
    navOrder: 10,
    legacyRouteKey: 'task-queue',
    migrationStatus: 'implemented',
    title: '任务队列',
    eyebrow: '自动化运营',
    summary: '查看任务运行、排队、失败与手动控制。',
  },
  {
    path: '/task-hall',
    name: 'task-hall',
    pageKind: 'placeholder',
    navGroup: 'automation',
    navOrder: 20,
    legacyRouteKey: 'task-hall',
    migrationStatus: 'placeholder',
    title: '任务大厅',
    eyebrow: '自动化任务大厅',
    summary: '把采集、互动、发布和回放任务统一成一张调度看板。',
  },
  {
    path: '/task-scheduler',
    aliases: ['/scheduler'],
    name: 'task-scheduler',
    pageKind: 'scheduler',
    navGroup: 'automation',
    navOrder: 30,
    legacyRouteKey: 'task-scheduler',
    migrationStatus: 'implemented',
    title: '任务调度',
    eyebrow: '自动化运营',
    summary: '管理计划任务、静默时段、启停切换与调度摘要。',
  },
  {
    path: '/scheduled-publish',
    name: 'scheduled-publish',
    pageKind: 'placeholder',
    navGroup: 'automation',
    navOrder: 40,
    legacyRouteKey: 'scheduled-publish',
    migrationStatus: 'placeholder',
    title: '定时发布',
    eyebrow: '发布编排中心',
    summary: '统一管理发布计划、草稿、审核状态和异常中断。',
  },
  {
    path: '/data-collector',
    name: 'data-collector',
    pageKind: 'placeholder',
    navGroup: 'automation',
    navOrder: 50,
    legacyRouteKey: 'data-collector',
    migrationStatus: 'placeholder',
    title: '数据采集助手',
    eyebrow: '采集工作流中心',
    summary: '统一管理采集任务、数据源、代理池和补偿链路。',
  },
  {
    path: '/auto-like',
    name: 'auto-like',
    pageKind: 'placeholder',
    navGroup: 'automation',
    navOrder: 60,
    legacyRouteKey: 'auto-like',
    migrationStatus: 'placeholder',
    title: '自动点赞',
    eyebrow: '互动增量控制台',
    summary: '按账号池、时间窗和互动目标配置点赞任务。',
  },
  {
    path: '/auto-comment',
    name: 'auto-comment',
    pageKind: 'placeholder',
    navGroup: 'automation',
    navOrder: 70,
    legacyRouteKey: 'auto-comment',
    migrationStatus: 'placeholder',
    title: '自动评论',
    eyebrow: '评论自动化控制台',
    summary: '统一管理评论模板、敏感词和账号节流规则。',
  },
  {
    path: '/auto-message',
    name: 'auto-message',
    pageKind: 'placeholder',
    navGroup: 'automation',
    navOrder: 80,
    legacyRouteKey: 'auto-message',
    migrationStatus: 'placeholder',
    title: '自动私信',
    eyebrow: '私信触达控制台',
    summary: '把私信触达、分层策略和频率限制集中展示。',
  },
  {
    path: '/auto-reply',
    name: 'auto-reply',
    pageKind: 'placeholder',
    navGroup: 'automation',
    navOrder: 90,
    legacyRouteKey: 'auto-reply',
    migrationStatus: 'placeholder',
    title: '自动回复',
    eyebrow: '自动回复工作台',
    summary: '管理规则命中、风险词、人工接管阈值和灰度发布状态。',
  },
  {
    path: '/creative-workshop',
    name: 'creative-workshop',
    pageKind: 'placeholder',
    navGroup: 'content',
    navOrder: 10,
    legacyRouteKey: 'creative-workshop',
    migrationStatus: 'placeholder',
    title: '创意工坊',
    eyebrow: '创意组合实验区',
    summary: '围绕主题、镜头、口播和素材组合做创意试验。',
  },
  {
    path: '/visual-lab',
    name: 'visual-lab',
    pageKind: 'placeholder',
    navGroup: 'content',
    navOrder: 20,
    legacyRouteKey: 'visual-lab',
    migrationStatus: 'placeholder',
    title: '可视化实验室',
    eyebrow: '视觉实验区',
    summary: '承接视觉方案探索、样式试验和页面对比。',
  },
  {
    path: '/ai-content-factory',
    name: 'ai-content-factory',
    pageKind: 'placeholder',
    navGroup: 'content',
    navOrder: 30,
    legacyRouteKey: 'ai-content-factory',
    migrationStatus: 'placeholder',
    title: 'AI 内容工厂',
    eyebrow: '内容创作',
    summary: '统一管理标题、脚本、文案和素材组合产出。',
  },
  {
    path: '/ai-copywriter',
    name: 'ai-copywriter',
    pageKind: 'copywriter',
    navGroup: 'content',
    navOrder: 40,
    legacyRouteKey: 'ai-copywriter',
    migrationStatus: 'implemented',
    title: 'AI 文案生成',
    eyebrow: '内容创作',
    summary: '通过真实 runtime 链路生成文案与流式结果。',
  },
  {
    path: '/viral-title',
    name: 'viral-title',
    pageKind: 'placeholder',
    navGroup: 'content',
    navOrder: 50,
    legacyRouteKey: 'viral-title',
    migrationStatus: 'placeholder',
    title: '爆款标题',
    eyebrow: '标题实验室',
    summary: '聚焦标题方向生成、比较和筛选。',
  },
  {
    path: '/script-extractor',
    name: 'script-extractor',
    pageKind: 'placeholder',
    navGroup: 'content',
    navOrder: 60,
    legacyRouteKey: 'script-extractor',
    migrationStatus: 'placeholder',
    title: '脚本提取',
    eyebrow: '脚本工作台',
    summary: '用于提取、改写和整理脚本素材。',
  },
  {
    path: '/product-title',
    name: 'product-title',
    pageKind: 'placeholder',
    navGroup: 'content',
    navOrder: 70,
    legacyRouteKey: 'product-title',
    migrationStatus: 'placeholder',
    title: '商品标题',
    eyebrow: '商品内容工作台',
    summary: '围绕商品卖点与平台规则生成标题。',
  },
  {
    path: '/video-editor',
    name: 'video-editor',
    pageKind: 'placeholder',
    navGroup: 'content',
    navOrder: 80,
    legacyRouteKey: 'video-editor',
    migrationStatus: 'placeholder',
    title: '视频编辑',
    eyebrow: '视频生产',
    summary: '承接时间轴、片段、字幕和导出工作流。',
  },
  {
    path: '/visual-editor',
    name: 'visual-editor',
    pageKind: 'placeholder',
    navGroup: 'content',
    navOrder: 90,
    legacyRouteKey: 'visual-editor',
    migrationStatus: 'placeholder',
    title: '可视化编辑',
    eyebrow: '视觉编辑器',
    summary: '承接图形化内容编辑和视觉拼版流程。',
  },
  {
    path: '/providers',
    aliases: ['/ai-provider'],
    name: 'ai-provider',
    pageKind: 'providers',
    navGroup: 'content',
    navOrder: 100,
    legacyRouteKey: 'ai-provider',
    migrationStatus: 'implemented',
    title: 'AI 提供商',
    eyebrow: '系统配置',
    summary: '统一维护模型提供商、连通性与默认模型配置。',
  },
  {
    path: '/traffic-board',
    name: 'traffic-board',
    pageKind: 'placeholder',
    navGroup: 'analysis',
    navOrder: 10,
    legacyRouteKey: 'traffic-board',
    migrationStatus: 'placeholder',
    title: '流量看板',
    eyebrow: '流量分析',
    summary: '聚合真实账号、任务与活动记录形成流量视图。',
  },
  {
    path: '/profit-analysis',
    name: 'profit-analysis',
    pageKind: 'placeholder',
    navGroup: 'analysis',
    navOrder: 20,
    legacyRouteKey: 'profit-analysis',
    migrationStatus: 'placeholder',
    title: '利润分析',
    eyebrow: '经营分析',
    summary: '查看利润相关指标与经营准备度趋势。',
  },
  {
    path: '/competitor-monitor',
    name: 'competitor-monitor',
    pageKind: 'placeholder',
    navGroup: 'analysis',
    navOrder: 30,
    legacyRouteKey: 'competitor-monitor',
    migrationStatus: 'placeholder',
    title: '竞品监控',
    eyebrow: '竞品分析',
    summary: '集中查看竞品样本、地区分布和异常任务提示。',
  },
  {
    path: '/blue-ocean',
    name: 'blue-ocean',
    pageKind: 'placeholder',
    navGroup: 'analysis',
    navOrder: 40,
    legacyRouteKey: 'blue-ocean',
    migrationStatus: 'placeholder',
    title: '蓝海机会',
    eyebrow: '机会探索',
    summary: '基于真实账号地区、素材类型和任务反馈生成机会线索。',
  },
  {
    path: '/report-center',
    name: 'report-center',
    pageKind: 'placeholder',
    navGroup: 'analysis',
    navOrder: 50,
    legacyRouteKey: 'report-center',
    migrationStatus: 'placeholder',
    title: '报表中心',
    eyebrow: '经营报表',
    summary: '统一查看日报、周报、专题报表和导出记录。',
  },
  {
    path: '/interaction-analysis',
    name: 'interaction-analysis',
    pageKind: 'placeholder',
    navGroup: 'analysis',
    navOrder: 60,
    legacyRouteKey: 'interaction-analysis',
    migrationStatus: 'placeholder',
    title: '互动分析',
    eyebrow: '互动洞察',
    summary: '聚合互动样本、情绪趋势和任务反馈。',
  },
  {
    path: '/ecommerce-conversion',
    name: 'ecommerce-conversion',
    pageKind: 'placeholder',
    navGroup: 'analysis',
    navOrder: 70,
    legacyRouteKey: 'ecommerce-conversion',
    migrationStatus: 'placeholder',
    title: '电商转化',
    eyebrow: '转化分析',
    summary: '查看电商漏斗、转化表现和阻塞环节。',
  },
  {
    path: '/fan-profile',
    name: 'fan-profile',
    pageKind: 'placeholder',
    navGroup: 'analysis',
    navOrder: 80,
    legacyRouteKey: 'fan-profile',
    migrationStatus: 'placeholder',
    title: '粉丝画像',
    eyebrow: '用户洞察',
    summary: '展示真实账号画像、兴趣簇和任务反馈的人群结构。',
  },
  {
    path: '/setup-wizard',
    name: 'setup-wizard',
    pageKind: 'setup',
    navGroup: 'system',
    navOrder: 10,
    legacyRouteKey: 'setup-wizard',
    migrationStatus: 'implemented',
    title: '初始化向导',
    eyebrow: '系统与工具',
    summary: '引导完成许可、提供商与基础环境初始化。',
  },
  {
    path: '/settings',
    aliases: ['/system-settings'],
    name: 'system-settings',
    pageKind: 'settings',
    navGroup: 'system',
    navOrder: 20,
    legacyRouteKey: 'system-settings',
    migrationStatus: 'implemented',
    title: '系统设置',
    eyebrow: '系统与工具',
    summary: '统一维护主题、系统参数与运行环境设置。',
  },
  {
    path: '/downloader',
    name: 'downloader',
    pageKind: 'placeholder',
    navGroup: 'system',
    navOrder: 30,
    legacyRouteKey: 'downloader',
    migrationStatus: 'placeholder',
    title: '下载器',
    eyebrow: '下载链路控制台',
    summary: '集中处理下载任务、代理链路、缓存目录和失败重试。',
  },
  {
    path: '/lan-transfer',
    name: 'lan-transfer',
    pageKind: 'placeholder',
    navGroup: 'system',
    navOrder: 40,
    legacyRouteKey: 'lan-transfer',
    migrationStatus: 'placeholder',
    title: '局域网传输',
    eyebrow: '局域网传输中枢',
    summary: '聚合同网设备发现、文件传输和进度状态。',
  },
  {
    path: '/network-diagnostics',
    name: 'network-diagnostics',
    pageKind: 'placeholder',
    navGroup: 'system',
    navOrder: 50,
    legacyRouteKey: 'network-diagnostics',
    migrationStatus: 'placeholder',
    title: '网络诊断',
    eyebrow: '网络健康中心',
    summary: '统一查看代理、下载、DNS、接口与延迟测试结果。',
  },
  {
    path: '/log-center',
    name: 'log-center',
    pageKind: 'placeholder',
    navGroup: 'system',
    navOrder: 60,
    legacyRouteKey: 'log-center',
    migrationStatus: 'placeholder',
    title: '日志中心',
    eyebrow: '日志观测中心',
    summary: '统一查看系统日志、异常级别、模块分布和导出记录。',
  },
  {
    path: '/version-upgrade',
    name: 'version-upgrade',
    pageKind: 'placeholder',
    navGroup: 'system',
    navOrder: 70,
    legacyRouteKey: 'version-upgrade',
    migrationStatus: 'placeholder',
    title: '版本升级',
    eyebrow: '版本升级中心',
    summary: '检查最新版本、查看更新日志、下载与安装新版。',
  },
  {
    path: '/license-issuer',
    name: 'license-issuer',
    pageKind: 'placeholder',
    navGroup: 'system',
    navOrder: 80,
    legacyRouteKey: 'license-issuer',
    migrationStatus: 'placeholder',
    title: '授权签发',
    eyebrow: '授权管理',
    summary: '管理许可签发、机器码绑定和授权状态。',
  },
  {
    path: '/permission-management',
    name: 'permission-management',
    pageKind: 'placeholder',
    navGroup: 'system',
    navOrder: 90,
    legacyRouteKey: 'permission-management',
    migrationStatus: 'placeholder',
    title: '权限管理',
    eyebrow: '权限与角色管理',
    summary: '管理角色、功能权限和操作审计日志。',
  },
];
